
spring:
  application:
    name: PSB_Click
#  datasource:
#    url: jdbc:postgresql://localhost:5432/notification_db
#    username: admin
#    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true

server:
  port: 8060

variable:
  partnerId: 8718971
  partnerKey: 2a5f578b756cfe5acb87f92d3e8ac5c6effc9469a45d14699cdef29c44df1a9d
  baseUrl: https://api.click.uz/partner
  requestTimeOut: 5_000
  jsonrpc: 2.0
  proxyHost: 172.25.42.77
  proxyPort: 808



